export const TireObj = {
  TIRE: {
    WORN_MINOR: {
      label: 'Is Slightly Worn',
      description: 'Shows signs of slight wear is should not need replacing.',
      tolerance: 'The tire looks almost new and has very little signs of wear.',
      repair_method: 'Report',
      repair_type: 'INFO',
      unit_measure: 'Per Component',
      grade_score: 0,
    },
    WORN_MEDIUM: {
      label: 'Is Medium Worn',
      description: 'Shows signs of medium wear and may need replacing.',
      tolerance: 'The tire does not look new and has some signs of wear.',
      repair_method: 'Replace',
      repair_type: 'SMART Repair',
      unit_measure: 'Per Component',
      grade_score: 3,
    },
    WORN_MAJOR: {
      label: 'Is Majorly Worn',
      description: 'Shows signs of major wear and needs replacing.',
      tolerance: 'The tire has major signs of wear.',
      repair_method: 'Replace',
      repair_type: 'SMART Repair',
      unit_measure: 'Per Component',
      grade_score: 3,
    },
    LIKE_NEW: {
      label: 'Tire Is Good',
      description: 'Shows signs of being recently replaced.',
      tolerance: 'The tire looks new with no signs of wear.',
      repair_method: 'Report',
      repair_type: 'INFO',
      unit_measure: 'Per Component',
      grade_score: 0,
    },
    WINTER_TREAD: {
      label: 'Is A Winter Tire',
      description:
        'Shows signs of being a winter or mud tire and may need replacing.',
      tolerance: 'The tire tread is for use in mud or snow.',
      repair_method: 'Report',
      repair_type: 'SMART Repair',
      unit_measure: 'Per Component',
      grade_score: 0,
    },
    BULGED: {
      label: 'Has Protrusion On Sidewall',
      description: 'Has a bulge on the sidewall and needs replacing.',
      tolerance: 'The tire tread has bulged spot.',
      repair_method: 'Replace',
      repair_type: 'SMART Repair',
      unit_measure: 'Per Component',
      grade_score: 3,
    },
    WEATHER_CRACKED: {
      label: 'Tread Is Weather Cracked',
      description: 'Shows signs of weather cracking and needs replacing.',
      tolerance: 'The tire tread has cracks in rubber.',
      repair_method: 'Replace',
      repair_type: 'SMART Repair',
      unit_measure: 'Per Component',
      grade_score: 3,
    },
    MISSMATCH_TIRE: {
      label: 'Tire Brand Does Not Match',
      description: 'Brand does not match other tires and needs replacing.',
      tolerance: 'The tire brand or size does not match the others.',
      repair_method: 'Replace',
      repair_type: 'SMART Repair',
      unit_measure: 'Per Component',
      grade_score: 3,
    },
    FLAT_TIRE: {
      label: 'This tire is low on air or is flat',
      description: 'The tire is flat and may need to be replaced',
      tolerance: 'Flat  tires are not acceptable',
      repair_method: 'Replace',
      repair_type: 'SMART',
      unit_measure: 'Per Component',
      grade_score: 2,
    },
  },
};
