export const DataSubmitDisclosure = (type) => {
  return {
    VEHICLE_DISCLOSURES: {
      OUTSTANDING_FINANCE: type['OUTSTANDING_FINANCE'],
      TOTAL_LOSS: type['TOTAL_LOSS'],
      STOLEN_AND_RECOVERED: type['STOLEN_AND_RECOVERED'],
    },
    ODOMETER: {
      ODOM_FAULTY: type['ODOMETER_BROKEN_FAULTY'],

      ODOM_REPLACED: type['ODOMETER_REPLACED'],
      ODOM_UNREADABLE: type['ODOMETER_UNREADABLE'],

      RMU: type['RECENT_MILES_UNKNOWN'],
    },
    DAMAGE: {
      ACCIDENT_REPAIR: type['ACCIDENT_REPAIR'],
      ADJACENT_PANELS_REPLACED: type['ADJACENT_PANELS_REPLACED'],
      EXCESSIVE_RUST: type['EXCESSIVE_RUST'],
      FLOOD_FIRE_DAMAGE: type['FLOOD_FIRE_DAMAGE'],
      AIR_BAG_DEFECTIVE: type['AIR_BAGS_MISSING_DEFECTIVE'],
      STRUCTURAL_DAMAGE: type['STRUCTURAL_DAMAGE'],
      MAJOR_REPAIR: type['MAJOR_REPAIR_NEEDED'],
      ALTERNATE_FUEL: type['ALTERNATE_FUEL_OR_CONVERSION'],
      CAR_WONT_START: type['CAR_WONT_START'],
      ANTILOCK_BRAKES_INOPERABLE: type['ANTILOCK_BRAKES_INOPERABLE'],
    },
    // MECHANICAL: {
    //   ABS_DEFECTIVE: type['ABS_DEFECTIVE'],
    //   AIR_BAG_DEFECTIVE:
    //     type['AIR_BAGS_MISSING/DEFECTIVE'] || type['AIR_BAG_DEFECTIVE'],
    //   ALTERNATE_FUEL:
    //     type['ALTERNATE_FUEL_OR_CONVERSION'] || type['ALTERNATE_FUEL'],
    //   NONE_SPECS:
    //     type['MATERIAL_VARIATION_FROM_PRODUCTION_SPECS'] || type['NONE_SPECS'],
    //   MAJOR_REPAIR: type['MAJOR_REPAIR_NEEDED'] || type['MAJOR_REPAIR'],
    // },
    'PREVIOUS USER': {
      PREVIOUS_DAILY_RENTAL: type['PREVIOUS_DAILY_RENTAL'],
      PREVIOUS_POLICE_VEHICLE: type['PREVIOUS_POLICE_VEHICLE'],
      PREVIOUS_TAXI_LIMO: type['PREVIOUS_TAXI_LIMO'],
    },
  };
};

export const DataSubmitAnnouncement = (type) => {
  return {
    REGISTRATION: type['REGISTRATION_DOCUMENTS_PRESENT?'],
    ALL_KEYS_PRESENT: type['ALL_KEYS_ARE_PRESENT?'],
    BOOKS_PRESENT: type[`ARE_ALL_SERVICE,_WARRANTY_AND_OWNERS_MANUAL_PRESENT?`],
    DISCS_PRESENT: type['ALL_SOFTWARE_AND_NAVIGATION_DISCS_ARE_PRESENT?'],
    RIMS_TYRES:
      type['IF_AFTERMARKET_WINTER_TYRES_AND_RIMS,_ARE_ORIGINALS_INCLUDED?'],
    OTHER_ANNOUNCEMENTS: type['ANY_OTHER_ANNOUNCEMENTS?'],
  };
};
